// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: dev-queries.sql

package db

import (
	"context"
	"database/sql"
)

const CreateConversation = `-- name: CreateConversation :one
INSERT INTO conversations (project_id) VALUES (?) RETURNING id, project_id, started_at
`

func (q *Queries) CreateConversation(ctx context.Context, projectID int64) (*Conversation, error) {
	row := q.db.QueryRowContext(ctx, CreateConversation, projectID)
	var i Conversation
	err := row.Scan(&i.ID, &i.ProjectID, &i.StartedAt)
	return &i, err
}

const CreateProject = `-- name: CreateProject :one
INSERT INTO projects (name, description, boilerplate, slug, network_id) VALUES (?, ?, ?, ?, ?) RETURNING id, name, description, boilerplate, created_at, updated_at, slug, container_id, container_name, status, last_started_at, last_stopped_at, container_port, network_id
`

type CreateProjectParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Boilerplate sql.NullString `json:"boilerplate"`
	Slug        string         `json:"slug"`
	NetworkID   sql.NullInt64  `json:"networkId"`
}

func (q *Queries) CreateProject(ctx context.Context, arg *CreateProjectParams) (*Project, error) {
	row := q.db.QueryRowContext(ctx, CreateProject,
		arg.Name,
		arg.Description,
		arg.Boilerplate,
		arg.Slug,
		arg.NetworkID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Boilerplate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.ContainerID,
		&i.ContainerName,
		&i.Status,
		&i.LastStartedAt,
		&i.LastStoppedAt,
		&i.ContainerPort,
		&i.NetworkID,
	)
	return &i, err
}

const DeleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteProject, id)
	return err
}

const GetDefaultConversationForProject = `-- name: GetDefaultConversationForProject :one
SELECT id, project_id, started_at FROM conversations WHERE project_id = ? ORDER BY started_at ASC LIMIT 1
`

func (q *Queries) GetDefaultConversationForProject(ctx context.Context, projectID int64) (*Conversation, error) {
	row := q.db.QueryRowContext(ctx, GetDefaultConversationForProject, projectID)
	var i Conversation
	err := row.Scan(&i.ID, &i.ProjectID, &i.StartedAt)
	return &i, err
}

const GetProject = `-- name: GetProject :one
SELECT id, name, description, boilerplate, created_at, updated_at, slug, container_id, container_name, status, last_started_at, last_stopped_at, container_port, network_id FROM projects WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id int64) (*Project, error) {
	row := q.db.QueryRowContext(ctx, GetProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Boilerplate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.ContainerID,
		&i.ContainerName,
		&i.Status,
		&i.LastStartedAt,
		&i.LastStoppedAt,
		&i.ContainerPort,
		&i.NetworkID,
	)
	return &i, err
}

const GetProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, name, description, boilerplate, created_at, updated_at, slug, container_id, container_name, status, last_started_at, last_stopped_at, container_port, network_id FROM projects WHERE slug = ?
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (*Project, error) {
	row := q.db.QueryRowContext(ctx, GetProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Boilerplate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.ContainerID,
		&i.ContainerName,
		&i.Status,
		&i.LastStartedAt,
		&i.LastStoppedAt,
		&i.ContainerPort,
		&i.NetworkID,
	)
	return &i, err
}

const InsertMessage = `-- name: InsertMessage :one
INSERT INTO messages (conversation_id, parent_id, sender, content) VALUES (?, ?, ?, ?) RETURNING id, conversation_id, parent_id, sender, content, created_at
`

type InsertMessageParams struct {
	ConversationID int64         `json:"conversationId"`
	ParentID       sql.NullInt64 `json:"parentId"`
	Sender         string        `json:"sender"`
	Content        string        `json:"content"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg *InsertMessageParams) (*Message, error) {
	row := q.db.QueryRowContext(ctx, InsertMessage,
		arg.ConversationID,
		arg.ParentID,
		arg.Sender,
		arg.Content,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.ParentID,
		&i.Sender,
		&i.Content,
		&i.CreatedAt,
	)
	return &i, err
}

const InsertToolCall = `-- name: InsertToolCall :one
INSERT INTO tool_calls (message_id, tool_name, arguments, result, error)
VALUES (?, ?, ?, ?, ?) RETURNING id, message_id, tool_name, arguments, result, error, created_at
`

type InsertToolCallParams struct {
	MessageID int64          `json:"messageId"`
	ToolName  string         `json:"toolName"`
	Arguments string         `json:"arguments"`
	Result    sql.NullString `json:"result"`
	Error     sql.NullString `json:"error"`
}

func (q *Queries) InsertToolCall(ctx context.Context, arg *InsertToolCallParams) (*ToolCall, error) {
	row := q.db.QueryRowContext(ctx, InsertToolCall,
		arg.MessageID,
		arg.ToolName,
		arg.Arguments,
		arg.Result,
		arg.Error,
	)
	var i ToolCall
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.ToolName,
		&i.Arguments,
		&i.Result,
		&i.Error,
		&i.CreatedAt,
	)
	return &i, err
}

const ListConversationsForProject = `-- name: ListConversationsForProject :many
SELECT id, project_id, started_at FROM conversations WHERE project_id = ? ORDER BY started_at ASC
`

func (q *Queries) ListConversationsForProject(ctx context.Context, projectID int64) ([]*Conversation, error) {
	rows, err := q.db.QueryContext(ctx, ListConversationsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(&i.ID, &i.ProjectID, &i.StartedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListMessagesForConversation = `-- name: ListMessagesForConversation :many
SELECT id, conversation_id, parent_id, sender, content, created_at FROM messages WHERE conversation_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListMessagesForConversation(ctx context.Context, conversationID int64) ([]*Message, error) {
	rows, err := q.db.QueryContext(ctx, ListMessagesForConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.ParentID,
			&i.Sender,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListProjects = `-- name: ListProjects :many
SELECT id, name, description, boilerplate, created_at, updated_at, slug, container_id, container_name, status, last_started_at, last_stopped_at, container_port, network_id FROM projects ORDER BY created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]*Project, error) {
	rows, err := q.db.QueryContext(ctx, ListProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Boilerplate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Slug,
			&i.ContainerID,
			&i.ContainerName,
			&i.Status,
			&i.LastStartedAt,
			&i.LastStoppedAt,
			&i.ContainerPort,
			&i.NetworkID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListToolCallsForConversation = `-- name: ListToolCallsForConversation :many
SELECT tc.id, tc.message_id, tc.tool_name, tc.arguments, tc.result, tc.error, tc.created_at FROM tool_calls tc
JOIN messages m ON tc.message_id = m.id
WHERE m.conversation_id = ?
ORDER BY tc.created_at ASC
`

func (q *Queries) ListToolCallsForConversation(ctx context.Context, conversationID int64) ([]*ToolCall, error) {
	rows, err := q.db.QueryContext(ctx, ListToolCallsForConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ToolCall{}
	for rows.Next() {
		var i ToolCall
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.ToolName,
			&i.Arguments,
			&i.Result,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListToolCallsForMessage = `-- name: ListToolCallsForMessage :many
SELECT id, message_id, tool_name, arguments, result, error, created_at FROM tool_calls WHERE message_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListToolCallsForMessage(ctx context.Context, messageID int64) ([]*ToolCall, error) {
	rows, err := q.db.QueryContext(ctx, ListToolCallsForMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ToolCall{}
	for rows.Next() {
		var i ToolCall
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.ToolName,
			&i.Arguments,
			&i.Result,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateProjectContainerInfo = `-- name: UpdateProjectContainerInfo :exec
UPDATE projects
SET
  container_id = ?,
  container_name = ?,
  status = ?,
  last_started_at = ?,
  last_stopped_at = ?,
  container_port = ?
WHERE id = ?
`

type UpdateProjectContainerInfoParams struct {
	ContainerID   sql.NullString `json:"containerId"`
	ContainerName sql.NullString `json:"containerName"`
	Status        sql.NullString `json:"status"`
	LastStartedAt sql.NullTime   `json:"lastStartedAt"`
	LastStoppedAt sql.NullTime   `json:"lastStoppedAt"`
	ContainerPort sql.NullInt64  `json:"containerPort"`
	ID            int64          `json:"id"`
}

func (q *Queries) UpdateProjectContainerInfo(ctx context.Context, arg *UpdateProjectContainerInfoParams) error {
	_, err := q.db.ExecContext(ctx, UpdateProjectContainerInfo,
		arg.ContainerID,
		arg.ContainerName,
		arg.Status,
		arg.LastStartedAt,
		arg.LastStoppedAt,
		arg.ContainerPort,
		arg.ID,
	)
	return err
}
