// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddRevokedCertificate(ctx context.Context, arg *AddRevokedCertificateParams) error
	CheckNetworkNodeExists(ctx context.Context, arg *CheckNetworkNodeExistsParams) (int64, error)
	CountBackupsBySchedule(ctx context.Context, scheduleID sql.NullInt64) (int64, error)
	CountBackupsByTarget(ctx context.Context, targetID int64) (int64, error)
	CountNetworks(ctx context.Context) (int64, error)
	CountNodeEvents(ctx context.Context, nodeID int64) (int64, error)
	CountNodes(ctx context.Context) (int64, error)
	CountNodesByPlatform(ctx context.Context, platform string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateBackup(ctx context.Context, arg *CreateBackupParams) (*Backup, error)
	CreateBackupSchedule(ctx context.Context, arg *CreateBackupScheduleParams) (*BackupSchedule, error)
	CreateBackupTarget(ctx context.Context, arg *CreateBackupTargetParams) (*BackupTarget, error)
	CreateFabricOrganization(ctx context.Context, arg *CreateFabricOrganizationParams) (*FabricOrganization, error)
	CreateKey(ctx context.Context, arg *CreateKeyParams) (*Key, error)
	CreateKeyProvider(ctx context.Context, arg *CreateKeyProviderParams) (*KeyProvider, error)
	CreateNetwork(ctx context.Context, arg *CreateNetworkParams) (*Network, error)
	CreateNetworkFull(ctx context.Context, arg *CreateNetworkFullParams) (*Network, error)
	// Add queries for CRUD operations
	CreateNetworkNode(ctx context.Context, arg *CreateNetworkNodeParams) (*NetworkNode, error)
	CreateNode(ctx context.Context, arg *CreateNodeParams) (*Node, error)
	CreateNodeEvent(ctx context.Context, arg *CreateNodeEventParams) (*NodeEvent, error)
	CreateNotificationProvider(ctx context.Context, arg *CreateNotificationProviderParams) (*NotificationProvider, error)
	CreateSession(ctx context.Context, arg *CreateSessionParams) (*Session, error)
	CreateSetting(ctx context.Context, config string) (*Setting, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	DeleteBackup(ctx context.Context, id int64) error
	DeleteBackupSchedule(ctx context.Context, id int64) error
	DeleteBackupTarget(ctx context.Context, id int64) error
	DeleteBackupsBySchedule(ctx context.Context, scheduleID sql.NullInt64) error
	DeleteBackupsByTarget(ctx context.Context, targetID int64) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteFabricOrganization(ctx context.Context, id int64) error
	DeleteKey(ctx context.Context, id int64) error
	DeleteKeyProvider(ctx context.Context, id int64) error
	DeleteNetwork(ctx context.Context, id int64) error
	DeleteNetworkNode(ctx context.Context, arg *DeleteNetworkNodeParams) error
	DeleteNode(ctx context.Context, id int64) error
	DeleteNotificationProvider(ctx context.Context, id int64) error
	DeleteOldBackups(ctx context.Context, arg *DeleteOldBackupsParams) error
	DeleteRevokedCertificate(ctx context.Context, arg *DeleteRevokedCertificateParams) error
	DeleteSession(ctx context.Context, sessionID string) error
	DeleteSetting(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteUserSessions(ctx context.Context, userID int64) error
	DisableBackupSchedule(ctx context.Context, id int64) (*BackupSchedule, error)
	EnableBackupSchedule(ctx context.Context, id int64) (*BackupSchedule, error)
	GetAllKeys(ctx context.Context, arg *GetAllKeysParams) ([]*GetAllKeysRow, error)
	GetAllNodes(ctx context.Context) ([]*Node, error)
	GetBackup(ctx context.Context, id int64) (*Backup, error)
	GetBackupSchedule(ctx context.Context, id int64) (*BackupSchedule, error)
	GetBackupTarget(ctx context.Context, id int64) (*BackupTarget, error)
	GetBackupsByDateRange(ctx context.Context, arg *GetBackupsByDateRangeParams) ([]*Backup, error)
	GetBackupsByScheduleAndStatus(ctx context.Context, arg *GetBackupsByScheduleAndStatusParams) ([]*Backup, error)
	GetBackupsByStatus(ctx context.Context, status string) ([]*Backup, error)
	GetDefaultNotificationProvider(ctx context.Context, type_ string) (*NotificationProvider, error)
	GetDefaultNotificationProviderForType(ctx context.Context, notificationType interface{}) (*NotificationProvider, error)
	GetFabricOrganization(ctx context.Context, id int64) (*FabricOrganization, error)
	GetFabricOrganizationByID(ctx context.Context, id int64) (*FabricOrganization, error)
	GetFabricOrganizationByMSPID(ctx context.Context, mspID string) (*FabricOrganization, error)
	GetFabricOrganizationByMspID(ctx context.Context, mspID string) (*GetFabricOrganizationByMspIDRow, error)
	GetFabricOrganizationWithKeys(ctx context.Context, id int64) (*GetFabricOrganizationWithKeysRow, error)
	GetKey(ctx context.Context, id int64) (*GetKeyRow, error)
	GetKeyByEthereumAddress(ctx context.Context, ethereumAddress sql.NullString) (*GetKeyByEthereumAddressRow, error)
	GetKeyByID(ctx context.Context, id int64) (*GetKeyByIDRow, error)
	GetKeyCountByProvider(ctx context.Context, providerID int64) (int64, error)
	GetKeyProvider(ctx context.Context, id int64) (*KeyProvider, error)
	GetKeyProviderByDefault(ctx context.Context) (*KeyProvider, error)
	GetKeyProviderByID(ctx context.Context, id int64) (*KeyProvider, error)
	GetKeysByAlgorithm(ctx context.Context, algorithm string) ([]*Key, error)
	GetKeysByProviderAndCurve(ctx context.Context, arg *GetKeysByProviderAndCurveParams) ([]*Key, error)
	GetKeysCount(ctx context.Context) (int64, error)
	GetLatestNodeEvent(ctx context.Context, nodeID int64) (*NodeEvent, error)
	GetNetwork(ctx context.Context, id int64) (*Network, error)
	GetNetworkByName(ctx context.Context, name string) (*Network, error)
	GetNetworkByNetworkId(ctx context.Context, networkID sql.NullString) (*Network, error)
	GetNetworkCurrentConfigBlock(ctx context.Context, id int64) (sql.NullString, error)
	GetNetworkNode(ctx context.Context, arg *GetNetworkNodeParams) (*NetworkNode, error)
	GetNetworkNodes(ctx context.Context, networkID int64) ([]*GetNetworkNodesRow, error)
	GetNode(ctx context.Context, id int64) (*Node, error)
	GetNodeBySlug(ctx context.Context, slug string) (*Node, error)
	GetNodeEvent(ctx context.Context, id int64) (*NodeEvent, error)
	GetNotificationProvider(ctx context.Context, id int64) (*NotificationProvider, error)
	GetOldestBackupByTarget(ctx context.Context, targetID int64) (*Backup, error)
	GetOrdererPorts(ctx context.Context) ([]*GetOrdererPortsRow, error)
	GetOrganizationCRLInfo(ctx context.Context, id int64) (*GetOrganizationCRLInfoRow, error)
	GetPeerPorts(ctx context.Context) ([]*GetPeerPortsRow, error)
	GetProvidersByNotificationType(ctx context.Context, arg *GetProvidersByNotificationTypeParams) ([]*NotificationProvider, error)
	GetRecentCompletedBackups(ctx context.Context) ([]*Backup, error)
	GetRevokedCertificate(ctx context.Context, arg *GetRevokedCertificateParams) (*FabricRevokedCertificate, error)
	GetRevokedCertificateCount(ctx context.Context, fabricOrganizationID int64) (int64, error)
	GetRevokedCertificates(ctx context.Context, fabricOrganizationID int64) ([]*FabricRevokedCertificate, error)
	GetSession(ctx context.Context, sessionID string) (*GetSessionRow, error)
	GetSetting(ctx context.Context, id int64) (*Setting, error)
	GetUser(ctx context.Context, id int64) (*User, error)
	GetUserByUsername(ctx context.Context, username string) (*User, error)
	ListBackupSchedules(ctx context.Context) ([]*BackupSchedule, error)
	ListBackupTargets(ctx context.Context) ([]*BackupTarget, error)
	ListBackups(ctx context.Context, arg *ListBackupsParams) ([]*Backup, error)
	ListBackupsBySchedule(ctx context.Context, scheduleID sql.NullInt64) ([]*Backup, error)
	ListBackupsByTarget(ctx context.Context, targetID int64) ([]*Backup, error)
	ListFabricOrganizations(ctx context.Context) ([]*FabricOrganization, error)
	ListFabricOrganizationsWithKeys(ctx context.Context) ([]*ListFabricOrganizationsWithKeysRow, error)
	ListKeyProviders(ctx context.Context) ([]*KeyProvider, error)
	ListKeys(ctx context.Context, arg *ListKeysParams) ([]*ListKeysRow, error)
	ListNetworkNodesByNetwork(ctx context.Context, networkID int64) ([]*NetworkNode, error)
	ListNetworkNodesByNode(ctx context.Context, nodeID int64) ([]*NetworkNode, error)
	ListNetworks(ctx context.Context) ([]*Network, error)
	ListNodeEvents(ctx context.Context, arg *ListNodeEventsParams) ([]*NodeEvent, error)
	ListNodeEventsByType(ctx context.Context, arg *ListNodeEventsByTypeParams) ([]*NodeEvent, error)
	ListNodes(ctx context.Context, arg *ListNodesParams) ([]*Node, error)
	ListNodesByNetwork(ctx context.Context, arg *ListNodesByNetworkParams) ([]*Node, error)
	ListNodesByPlatform(ctx context.Context, arg *ListNodesByPlatformParams) ([]*Node, error)
	ListNotificationProviders(ctx context.Context) ([]*NotificationProvider, error)
	ListSettings(ctx context.Context) ([]*Setting, error)
	ListUsers(ctx context.Context) ([]*User, error)
	MarkBackupNotified(ctx context.Context, id int64) error
	UnsetDefaultNotificationProvider(ctx context.Context, type_ string) error
	UnsetDefaultProvider(ctx context.Context) error
	UpdateBackupCompleted(ctx context.Context, arg *UpdateBackupCompletedParams) (*Backup, error)
	UpdateBackupFailed(ctx context.Context, arg *UpdateBackupFailedParams) (*Backup, error)
	UpdateBackupSchedule(ctx context.Context, arg *UpdateBackupScheduleParams) (*BackupSchedule, error)
	UpdateBackupScheduleLastRun(ctx context.Context, arg *UpdateBackupScheduleLastRunParams) (*BackupSchedule, error)
	UpdateBackupSize(ctx context.Context, arg *UpdateBackupSizeParams) (*Backup, error)
	UpdateBackupStatus(ctx context.Context, arg *UpdateBackupStatusParams) (*Backup, error)
	UpdateBackupTarget(ctx context.Context, arg *UpdateBackupTargetParams) (*BackupTarget, error)
	UpdateDeploymentConfig(ctx context.Context, arg *UpdateDeploymentConfigParams) (*Node, error)
	UpdateFabricOrganization(ctx context.Context, arg *UpdateFabricOrganizationParams) (*FabricOrganization, error)
	UpdateKey(ctx context.Context, arg *UpdateKeyParams) (*Key, error)
	UpdateKeyProvider(ctx context.Context, arg *UpdateKeyProviderParams) (*KeyProvider, error)
	UpdateNetworkCurrentConfigBlock(ctx context.Context, arg *UpdateNetworkCurrentConfigBlockParams) error
	UpdateNetworkGenesisBlock(ctx context.Context, arg *UpdateNetworkGenesisBlockParams) (*Network, error)
	UpdateNetworkNodeRole(ctx context.Context, arg *UpdateNetworkNodeRoleParams) (*NetworkNode, error)
	UpdateNetworkNodeStatus(ctx context.Context, arg *UpdateNetworkNodeStatusParams) (*NetworkNode, error)
	UpdateNetworkStatus(ctx context.Context, arg *UpdateNetworkStatusParams) error
	UpdateNodeConfig(ctx context.Context, arg *UpdateNodeConfigParams) (*Node, error)
	UpdateNodeDeploymentConfig(ctx context.Context, arg *UpdateNodeDeploymentConfigParams) (*Node, error)
	UpdateNodeEndpoint(ctx context.Context, arg *UpdateNodeEndpointParams) (*Node, error)
	UpdateNodePublicEndpoint(ctx context.Context, arg *UpdateNodePublicEndpointParams) (*Node, error)
	UpdateNodeStatus(ctx context.Context, arg *UpdateNodeStatusParams) (*Node, error)
	UpdateNotificationProvider(ctx context.Context, arg *UpdateNotificationProviderParams) (*NotificationProvider, error)
	UpdateOrganizationCRL(ctx context.Context, arg *UpdateOrganizationCRLParams) error
	UpdateProviderTestResults(ctx context.Context, arg *UpdateProviderTestResultsParams) (*NotificationProvider, error)
	UpdateSetting(ctx context.Context, arg *UpdateSettingParams) (*Setting, error)
	UpdateUser(ctx context.Context, arg *UpdateUserParams) (*User, error)
	UpdateUserLastLogin(ctx context.Context, id int64) (*User, error)
}

var _ Querier = (*Queries)(nil)
